# Generated by Django 4.2.5 on 2024-10-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_task_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_list",
        ),
    ]
